# Generated by Django 5.0.2 on 2024-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
